-- Question- What percentage of total revenue is generated by the top 20% of customers, 
-- 			and how dependent is the business on this high-value customer group?

with customer_revenue as(select customer_id,
     sum(total_amount) as revenue 
from orders
join order_items using(order_id)
group by customer_id ),

ranked_customers as(select *,
   ntile(5) over (order by revenue desc) as customer_group
from customer_revenue )
select round(
          sum( case when customer_group=1 then revenue end )/sum(revenue)*100.0,
		2) as top_20_revenue_percentage
from ranked_customers;